name: Flutter Build Auto APK + AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸŸ¢ Checkout Code
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: ğŸ“¦ Get Dependencies
        run: flutter pub get

      - name: ğŸ—ï¸ Build APK
        run: flutter build apk --release

      - name: ğŸ§± Build AAB
        run: flutter build appbundle --release

      - name: ğŸ“¤ Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FlutterAppBuilds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
